#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

moduledir 'modules-contrib'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'stahnma/epel'
mod 'garethr/docker'

